name: 'Release with HEMTT'
description: 'Build your mod with HEMTT.'
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  zip_build:
      description: 'Zip the build'
      required: false
      default: 'true'
  cwd:
      description: 'Working directory'
      required: false
      default: '.'

outputs:
  zip_path:
    description: 'Relative path of packed mod'
  zip_name:
    description: 'Name of packed mod (without file extension)'
  release_path:
    description: 'Relative path of mod'

runs:
  using: 'node16'
  main: 'dist/index.js'
